### ISSUE TITLE
Comunicación vector fuerza Unity -> ROS2

### ISSUE THREAD

**Issue by Borailuce99** [ajardon/TFM-BorjaPerez#5]
En Unity se ha implementado el código para obtener el vector fuerza que sería necesario aplicar en el robot IIWA para obtener la asistencia para mantener la esfera del usuario dentro del laberinto.
Un poco en resumen sería:

- En la escena actualmente hay dos esfera, una kinemática **ROSA** (la posición total del robot en la escena) que no colisiona con nada y se mueve por libre por la escena. Y otra **AZUL** que colisiona con las paredes del laberinto intentando seguir a la kinemática y es la que correspondería a la bola del usuario. Estas se pueden apreciar en la imagen siguiente.

![imagen](https://user-images.githubusercontent.com/69549100/234303998-054c8083-e001-4efd-8461-e268ea59aa7e.png)

- A partir de estas 2 esferas, se obtienen los siguientes parámetros

    - Dirección: La dirección que debe tener la fuerza aplicada por el robot resulta de la resta entre la posición de la esfera AZUL y la posición de la esfera ROSA normalizada (vector unitario)

    - Distancia: Magnitud del vector que une ambas esferas y corresponde a la distancia real entre las mismas.
    - Factor de distancia: Corresponde a un float que hace que, cuanto más alejado se está del laberinto mayor será la fuerza aplicada desde el robot.
    - Proporcional: Float con valor para ajustar la magnitud de la fuerza del robot y limitarla si fuera necesario. (por defecto está con valor 1).
- De esta forma, al multiplicar estos parámetros, se obtiene un Vector3 que corresponde al vector fuerza a aplicar por el robot, con su dirección y magnitud en cada eje XYZ.

Por ello, a partir de este Vector3 se debería de poder aplicar la fuerza en el robot IIWA. De esta forma, en Unity se va continuamente publicando este vector fuerza en el topic "**/fb_force**" como un mensaje de tipo **RosMessageTypes.Geometry.PointMsg** al que se deberá suscribir el control del IIWA y emplear este vector para aplicar el feedback de fuerza.

No obstante, si es necesario algún otro parámetro o es mejor enviar alguna otra información como la dirección, distancia, etc... para que la procese el robot, también es posible.

**Comment by imontesino** [comment]
Con eso deberia bastar y deberias poder mover el robot simulado con el raton y comprobar que no se sale de las paredes del laberinto.

**Comment by imontesino** [comment]
@Borailuce99 Avisame en cuanto lo pruebes para aprovechar al maximo el tiempo que tenemos

**Comment by Borailuce99** [comment]
Buenas. He estado siguiendo los pasos que has ido indicando y me han surgido algunas dudas y errores:
- Me he descargado los respositorios que has comentado (tfm-borja, cobot-py y ros_iiwa_unity_msg). Luego en Unity con la herramienta Toolbox he añadido los mensajes, servicios y acciones de "ros_iiwa_unity_msg" a Unity como se ve en la imagen (aunque me ha dado un error con el mensaje "TrafficLight.msg" pero no le he dado más importancia.
![imagen](https://user-images.githubusercontent.com/69549100/234640033-b41c7c51-c3e2-470f-af37-db84bcc043fa.png)

- Luego, siguiendo el ejemplo para llamar al servicio de ROS en Unity que me has proporcionado, he visto que al definir la variable del servicio, pone "ros.RegisterRosService<PositionServiceRequest, PositionServiceResponse>(serviceName)" porque era el ejemplo de Position Service, pero en mi caso cual sería el nombre del servicio _serviceName_? E imagino que la llamada sería "srv.RegisterRosService<ControlModeServiceRequest, ControlModeServiceResponse>("coll_srv");".
- Al incluir el mensaje para el servicio, tengo una variable booleana que se pone a true cuando entra en contacto con algo y false cuando sale de la colisión. Por otro lado, la posición xyz de la esfera de dentro es una variable de tipo "Vector3". He 'convertido' esa variable creando un objeto "RosMessageTypes.Geometry.PointMsg" cuyas coordenadas xyz corresponden a las del Vector3. Sería así como se debería enviar el mensaje al servicio? Además, todo esto está en el bucle "Update" del script de Unity, por lo que se ejecuta siempre con al frecuencia definida por defecto en Unity, esté en colisión o no la esfera.
- Por último, al intentar seguir los pasos de la branch "tfm-borja", al ejecutar el docker-compose build ros2-dev en vs en la carpeta del repo "iiwa-ros2-examples" creada con 'git clone git@github.com:roboticslab-uc3m/iiwa-ros2-examples.git' me aparece el error **ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml**
He probado también al repo que tenía antes y usaba para la simulación (el de roboasset-ros2-pkgs) y he hecho un git pull, pero al ejecutar el docker-compose me ha seguido fallando. Tengo que hacer alguna otra modificación o descargar algo más para poder utilizar el docker de la branch tfm-borja? Perdona por las molestias, esque aún no manejo mucho docker y no entiendo muy bien cómo va o por qué salen los errores.

**Comment by imontesino** [comment]
@Borailuce99 
Respondiendo a tus dudas:

- el nombre del servicio es `/iiwa/id_1/set_control_mode`. Solo hay que cambiarlo antes de empezar a mandarle colisiones.
- con `x y z` hay un detalle con Unity y es que usa un sistema levógiro, con el `y` hacia arriba. Mira como hiciste los cambios al recibir la posición del robot para pintar la bola.
- No hace falta que uses el docker dado que no vas a conectarlo con el robot real, con que descargues esas repos en tu workspace de ROS y compiles bastaría.

**Comment by imontesino** [comment]
Por cierto, añádeme como colaborador a este repo

**Comment by imontesino** [comment]
- No, me refiero a que tienes que cambiar el modo de control a `COLLISION_POINT_HAPTIC` antes de mandar colisiones por el topic de colisiones. Cuando hacerlo es a discreción tuya según la lógica de tu programa que desconozco.
- Exacto, cambiar de sistema de cordanadas Unity a ROS
- Okey pues le dejamos eso a @ajardon

**Comment by ajardon** [comment]
> * No, me refiero a que tienes que cambiar el modo de control a `COLLISION_POINT_HAPTIC` antes de mandar colisiones por el topic de colisiones. Cuando hacerlo es a discreción tuya según la lógica de tu programa que desconozco.
> * Exacto, cambiar de sistema de cordanadas Unity a ROS
> * Okey pues le dejamos eso a @ajardon

@imontesino invitado¡¡¡

**Comment by imontesino** [comment]
prueba a pararlo y lanzarlo otra vez, ese error tiene pinta de mala comunicacion unity ros

**Comment by imontesino** [comment]
@Borailuce99 Podrías subir tu código de Unity a GitHub? Creo que el error el que has creado el publisher con el tipo de dato incorrecto.

**Comment by Borailuce99** [comment]
ya está subido. Es el "BallController.cs". Al principio del código están los tipos de mensajes de ROS que añado con el "using", por si es eso lo que quieres comprobar.

**Comment by imontesino** [comment]
Pues desconozco el origen del error, aparte de que en el código que has pasado hay muchas cosas comentadas que entiendo que será que estabas haciendo pruebas.

Prueba a bajarte la última versión del repo https://github.com/roboticslab-uc3m/roboasset-ros2-pkgs, esta vez en la rama `main` y recompilar el Docker. Esta versión está probada con Hugo, así que 100% no hay problema de conexión con Unity.

Así ideas rápidas:
 - añade un debug al `callback` del servicio para ver que se está ejecutando correctamente
 - Asegúrate de que tienes la IP correctamente puesta en los settings de ROS en Unity, si no me falla la memoria debería ser `0.0.0.0`

**Comment by Borailuce99** [comment]
He comprobado la IP que tenía en Unity y era "127.0.0.1:10000" así que la he cambiado a la que comentas, "0.0.0.0:10000" pero ahora me aparece el error en Unity de `Connection to 0.0.0.0:10000 failed - System.ArgumentException: Addresses 0.0.0.0 (IPv4) and ::0 (IPv6) are unspecified addresses. You cannot use them as target address.` Es posible que esa dirección no se pueda establecer para la conexión y tenga que ser un localhost (127.0.0.1) como antes? Estoy clonando y recompilando el docker que comentabas mientras, pero por si podía ser la IP el problema.

**Comment by Borailuce99** [comment]
Al probar con la rama `main` ejecuto el docker y luego en un terminal el ros_tcp_endpoint, y al intentar conectarse desde Unity (con la IP 127.0.0.1 aunque en el terminal ponga el 0.0.0.0) me aparece el error `No module named 'ros_iiwa_unity_msgs.ros_iiwa_unity_msgs_s__rosidl_typesupport_c`. Ya desconozco si es un tipo de mensaje de la librería o que has creado tú.

**Comment by imontesino** [comment]
El docker lleva el tcp endpoint integrado, no necesitas lanzar otro en una terminal. Mas aun, si lanzas otro puede dar problemas de comunicacion.

**Comment by Borailuce99** [comment]
En el docker de la rama main también?

**Comment by imontesino** [comment]
Si, recuerda seguir estos pasos pero con la rama main

> 
> ```shell
> python3 generate_env_file.py
> eval `ssh-agent -s`
> ssh-add ~/.ssh/id_rsa
> export DOCKER_BUILDKIT=1
> docker compose build demo
> ```
> 
> Una vez compilado para lanzarlo ejecuta los siguientes:
> 
> ```shell
> sudo xhost +
> docker compose run --rm labrynth-demo
> ```

**Comment by imontesino** [comment]
Eso es por que no se han recompilado los dockers. tienes dos opciones:

- recompilarlo con le comando:
```bash
docker compose build demo --no-cache
```

- Bajarte la ultima release con:
```bash
docker pull ghcr.io/roboticslab-uc3m/roboasset-demo:latest  
```
Para la segura tendras que primero identificarte siguiendo [estos pasos](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic)

A parte, revisa los pasos que te he dicho que sigas, el comando que tienes que funcione con tu programa es:
```bash
sudo xhost +
docker compose run --rm labrynth-demo
```

**Comment by Borailuce99** [comment]
Mientras se recompilaba, he modificado algunas cosas del código de Unity y al ejecutarlo, el servicio parece que funciona correctamente, en el terminal de vs me aparece:
`[robot_controller-1] [INFO] [1683543299.533012763] [iiwa_controler_id_1]: Got control mode: COLLISION_POINT_HAPTIC
[robot_controller-1] [INFO] [1683543299.534154975] [iiwa_controler_id_1]: IK succeeded with joint positions: [ 0.00670754  0.42741828 -0.01142893 -1.60052035  0.00556711  1.13582927
[robot_controller-1]  -0.00670798]
[robot_controller-1] [INFO] [1683543299.534541421] [iiwa_controler_id_1]: Switched to control mode: COLLISION_POINT_HAPTIC`
Por lo que entiendo que el mensaje de cambio de control a "COLLISION_POINT_HAPTIC" se está enviando correctamente.

Ahora el problema sigue siendo creo que el Publisher, que me salen diversos mensajes de que ese publisher ya está registrado, aunque al cambiar el código de Unity, si no poinía el "ros.RegisterPublisher" me salía otro error de que el publisher al que enviaba mensajes no estaba registrado.

**Comment by imontesino** [comment]
No, el docker no registra nada. el docker solo lanza el tcp enpoint. Ese warning suele ser que estas lanzando varias veces el programa y por lo tanto estas creando el publisher varias veces.

En esos casos prueba a lanzar todo de nuevo. primero el docker y luego el script de Unity.

Si persiste ese error tendra que buscar que significa por que son cosas de como usar Unity tcp endpoint.

**Comment by Borailuce99** [comment]
Buenas. Estoy intentado recompilar el docker y aunque haga con el `--no-cache` o borre el repo y vuelva a hacer git clone y vuelva a intentar el `build`, falla al intentar hacer `sudo pat-get update` y muestra los siguientes mensajes:

![imagen](https://github.com/ajardon/TFM-BorjaPerez/assets/69549100/91f1631a-0eb1-4c07-89b3-494d03d86858)

 Después de eso intenta el `sudo apt-get install -y software-properties-common`, falla y termina la ejecución.

**Comment by Borailuce99** [comment]
He estado buscando y probando a ver cuál podía ser el problema de registrar 2 publishers y en el respositorio de ROS-TCP-Connector he encontrado un par de issues relacionadas:
- https://github.com/Unity-Technologies/ROS-TCP-Connector/issues/299. En esta he visto que tiene el mismo problema que yo, que se crean 2 publishers con el mismo nombre aunque solo registres 1. Se publicó en octubre de 2022 pero no ha recibido respuesta alguna...
- https://github.com/Unity-Technologies/ROS-TCP-Connector/issues/248. Luego en este otro he visto que tenía un problema al ejecutar el publisher después del subscriber, y me ha dado la idea de hacerlo a la inversa de como estábamos, primero ejecutar Unity y que registre todos los topics y la instancia, y luego ejecutar el docker. **De esta forma he conseguido que funcionase sin que apareciera el error y parece que todo funciona correctamente y en unity no aparece ningún error tampoco**.
No obstante, aunque no aparezca ningún error, parece que unity no recibe ningún mensaje del topic `/iiwa/id_1/ee_pose` y por lo tanto la bola no se mueve aunque mueva el brazo del robot. Cuando intento hacer un `ros2 topic echo /iiwa/id_1/ee_pose` me aparece un error de "Cannot echo topic as it contains more than one type: [geometry_msgs/msg/Pose, geometry_msgs/msg/PoseStamped]". Es posible que el callback de Unity no se esté llamando porque solo tengo puesto un argumento de tipo PoseMsg? O por qué no se ejecuta el callback del suscriber? Cómo puedo hacer un echo para ver el mensaje que se está enviando por el topic?

**Comment by Borailuce99** [comment]
He probado ahora como ayer, ejecutando primero Unity y luego el docker, pero ahora ya no funciona y sigue fallando. No aparecen los nodos en rqt_graph como ayer ni nada.
he probado con Debug.Log en varias partes pero el registerPublisher solo se ejecuta 1 vez, no tengo ni idea de por qué da el fallo de registrarse 2 veces.

**Comment by Borailuce99** [comment]
Por cierto, de forma paralela a todo el intento de implementación esta, estoy haciendo el apartado de desarrollo de la parte del IIWA y diseñando el pipeline, me gustaría saber un poco más, aunque sea por encima y no muy en detalle, como funciona el apartado del labrynth-demo que has implementado @imontesino para añadirla al pipeline. Principalmente es la parte de recibir el mensaje de colisión en el `/iiwa/id_1/collision_point`del ROS-TCP y qué hace el robot con ese mensaje, cómo hace el control de las articulaciones para ejecutar esa función de fuerza, cómo el "controlador" procesa ese mensaje y qué envía luego al IIWA, etc...
Pero repito, si puedes, tampoco es necesario que entres muy en detalles y especificaciones, solo es para tener una pequeña idea superficial para plasmarla en la memoria.

Gracias.

**Comment by Borailuce99** [comment]
Se me ha ocurrido probar con una nueva escena básica. Tan solo una esfera que contiene un "testingROS.cs" que tiene una ROSConnection y un Subscriber que ejecuta una función que hace Debug.Log del mensaje recibido. Al ejecutar esta escena, sigue apareciendo el error de `NoneType objects has no attribute msg` y que el Publisher ya está registrado (aunque no registre ningún Publisher en la escena. Mirando los ejemplos del repo Unity-Robotics-Hub he visto que el código implementado es igual por lo que ya no sé qué es lo que puede estar fallando pero no parece que sea lo de que habían varios Publishers en Unity o que se repita el registro varias veces.

**Comment by Borailuce99** [comment]
Así se ha comprobado que el problema no era el warning que aparecía, si no la definición del Subscriber ya que no existe ningún topic `/ee_pose` de tipo `Pose` sino que era `PoseStamped`. Lo siguiente ahora sería comprobar si se está enviando correctamente la información del topic `/collision_point`.

Por otro lado, ¿sería posible restringir el movimiento del robot en la simulación a un plano 2D, para facilitar las pruebas ya que en Unity la esfera al transformar la posición del iiwa, se restringe a un solo plano 2D.

**Comment by imontesino** [comment]
Geniaaaal!!!  Si, seria posible restringirlo. Quiza sea interesante meter  esos parametros en el mensaje? De momento podriamos probarlo solo restringiendo el plano vertical delante del robot.

**Comment by Borailuce99** [comment]
Qué código he de modificar para restringir el movimiento?

> Geniaaaal!!! Si, seria posible restringirlo. Quiza sea interesante meter esos parametros en el mensaje? De momento podriamos probarlo solo restringiendo el plano vertical delante del robot.

**Comment by imontesino** [comment]
Por cierto @Borailuce99, he actualizado https://github.com/roboticslab-uc3m/roboasset-ros2-pkgs
Ahora hay una herramienta por terminal (`roboasset_cli`) para crear dockers, descargarse los ultimos, correr las demos, etc.
Si pudieras hecharle un vistazo, probarla y me dices si es intuitiva y si te funciona bien.

**Comment by boperezl** [comment]
- Sobre lo de la restricción del plano en `robot-controller` de acuerdo, ya me informas cuando esté cambiado para que lo pruebe.
- En cuanto a la explicación, mañana después de comer creo que tengo un ratillo antes de las 17:00, así que si estás en la uni y no tienes mucho lío, me puedo acercar al laboratorio y me lo comentas. Si no, el jueves creo que también puedo después de comer.
- Vale! Esta tarde le echo un vistazo y te comento cualquier cosa.

**Comment by imontesino** [comment]
Para actualizar tu docker primero haz pull de [roboticslab-uc3m/roboasset-ros2-pkgs](https://github.com/roboticslab-uc3m/roboasset-ros2-pkgs) para que tengas la nueva CLI.

Despues modifica el archivo `repos/iiwa_control.repos` en la linea que pone
```yaml
  dual-iiwa-control:
    type: git
    url: git@github.com:roboticslab-uc3m/dual-iiwa-control.git
    version: main
```
y cambia `main` por `tfm_borja`.

Despues usa la cli para recompilar el docker y cuando te pregunte si quieres actualizar los paquetes dale a `y`

**Comment by Borailuce99** [comment]
Vale, ahora ha fallado más adelante al hacer el apt. He probado la opcióin `c` de no-cache que ponía de usar si daba problemas el apt, pero ha vuelto a fallado también con `executor failed running [/bin/sh -c apt-get install -y npm]: exit code: 100`

**Comment by imontesino** [comment]
> Vale, ahora ha fallado más adelante al hacer el apt. He probado la opcióin `c` de no-cache que ponía de usar si daba problemas el apt, pero ha vuelto a fallado también con `executor failed running [/bin/sh -c apt-get install -y npm]: exit code: 100`

prueba otra vez, es la primera vez que falla esal linea. Asegurate que tienes conexion a internet estable y sin vpn o cosas asi.

**Comment by Borailuce99** [comment]
Okey, por otro lado al ejecutar con la opción `y` me aparecía este error:
#26 722.3   apt: command [apt-get install -y ros-foxy-cv-bridge] failed
#26 722.3   apt: Failed to detect successful installation of [ros-foxy-cv-bridge]
------
executor failed running [/bin/sh -c . /opt/ros/foxy/setup.sh &&     rosdep install --from-paths src --ignore-src --rosdistro foxy -y -r --dependency-types='build' &&     colcon build --cmake-args -DBUILD_TESTING=OFF]: exit code: 1

Es el mismo error que me daba antes al instalarlo. No tengo ninguna VPN en el portátil y el internet debería ser estable, por si acaso, voy a conectarlo directamente al router con ethernet por si fuera ese el problema.

**Comment by Borailuce99** [comment]
Finalmente, tras desconectarse el internet y luego apagarse el ordenador (-.-") ya ha funcionado el build correctamente! 
He ejecutado la imagen del labrynth-demo y me ha dado un error de "No protocol specified. cannot connect to X server".
Pero al ejecutar la imagen del roboasset-demo, sim_demo parece que sí que funciona correctamente.

**Comment by imontesino** [comment]
hay que darle acceso a los docker a la pantalla corriendo el comando:
```bash
xhost +local:root
```

Tambien lo he añadido a la opcion `Set-up environment` de la CLI

**Comment by imontesino** [comment]
@Borailuce99 añadido Nvidia a la CLI. haz pull de la repo y prueba.
Ahora la CLI es un programa que se instala. En el TLDR veien las intrucciones.
es solo hacer `pip install .`

Despues en la CLi ejecuta el setup para asegurarte que tienes todo lode NVIDIA

**Comment by Borailuce99** [comment]
He vuelto a probar lo del docker, pero me ha fallado al hacer el rebuild del docker (tanto con la opción **y** como con la **c**).
Aparece el siguiente error: `executor failed running [/bin/sh -c sudo apt-get install -y software-properties-common &&     sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&     sudo apt-get update && sudo apt-get install -y gcc-11 g++-11]: exit code: 100`
Seguido de un montón de traceback como este:

![imagen](https://github.com/ajardon/TFM-BorjaPerez/assets/69549100/acacf2e4-17da-4675-b0ad-fcd647c52be1)
![imagen](https://github.com/ajardon/TFM-BorjaPerez/assets/69549100/fcc86ced-ae88-4b35-95fb-720772a92521)

Los pasos que he seguido son:
1. `git pull`
2. `pip install .`
3. Modificar archivo repos > iiwa_control.repos para poner lo de `tfm/borja`
4. `roboasset-cli -d .`
5. Opción 3 de `setup` -> TODO SALE OK
6. Opción 2 de `Build` -> con la opción de NVIDIA
7. `roboasset_demo`
Y ya he probado las 2 opciones que he comentado antes y nada.

No sé si se me ha llegado a pasar algún paso de los que hemos hablado en el lab.

**Comment by imontesino** [comment]
Te puedes estar quedando sin espacio en el disco duro?

si puedes copiar y pegar e error que sale encima de lo que has mandado, el de docker build

**Comment by imontesino** [comment]
```bash
libGL error: MESA-LOADER: failed to retrieve device information
```
Es un error que tiene que ver con los drivers de la GPU, por eso tienes que hacer el buikld con nvidia.

Me resulta un poco imposible que tengas  4.6TB libres., a no set que tu disco duro sea de 8TB...
No seran gigas?
por que si es asi no es suficiente para hacer el build

**Comment by imontesino** [comment]
Tiene que ser mayor que 418. Cual tienes?

**Comment by imontesino** [comment]
por cierto ahora con `pip install --upgrade --no-deps --force-reinstall git+ssh://git@github.com/roboticslab-uc3m/roboasset-ros2-pkgs.git`
puedes instalar la ultima version de la CLI sin tener que  hacer pull de la repo.
Acabo de añadir el check para la version del driver y una herramienta para limpioar espacio de Docker

**Comment by Borailuce99** [comment]
Del nvidia-driver tengo la versión 515

**Comment by imontesino** [comment]
Intenta recompilar el docker i mandame lo que hay antes del traceback. Que sera el error en si de docker

**Comment by Borailuce99** [comment]
No si al final el recompilar el docker sí ha funcionado. Ha sido luego al ejecutar el labrynth-demo lo que ha fallado y sale el error completo:
----- Terminal Output -----
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-05-18-23-52-24-984733-bope-Victus-by-HP-Laptop-16-d0xxx-1
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_controller-1]: process started with pid [71]
[INFO] [1684446745.119524177] [UnityEndpoint]: Starting server on 0.0.0.0:10000
[robot_controller-1] pybullet build time: May 20 2022 19:44:17
[robot_controller-1] libGL error: MESA-LOADER: failed to retrieve device information
[robot_controller-1] Traceback (most recent call last):
[robot_controller-1]   File "/demo_ws/install/dual_iiwa_control/lib/dual_iiwa_control/robot_controller", line 11, in <module>
[robot_controller-1]     load_entry_point('dual-iiwa-control==0.0.0', 'console_scripts', 'robot_controller')()
[robot_controller-1]   File "/demo_ws/install/dual_iiwa_control/lib/python3.8/site-packages/dual_iiwa_control/robot_controller.py", line 658, in main
[robot_controller-1]     controller_node = RobotController(args.robot_id,
[robot_controller-1]   File "/demo_ws/install/dual_iiwa_control/lib/python3.8/site-packages/dual_iiwa_control/robot_controller.py", line 208, in __init__
[robot_controller-1]     self.robot = IiwaSim(robot_model=self.robot_urdf_file,
[robot_controller-1]   File "/demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/iiwa_pb.py", line 242, in __init__
[robot_controller-1]     self.start_connection()
[robot_controller-1]   File "/demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/iiwa_pb.py", line 357, in start_connection
[robot_controller-1]     self.start_simulation()
[robot_controller-1]   File "/demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/iiwa_pb.py", line 298, in start_simulation
[robot_controller-1]     raise TimeoutError("Pybullet server did not start in time")
[robot_controller-1] TimeoutError: Pybullet server did not start in time
[ERROR] [robot_controller-1]: process has died [pid 71, exit code 1, cmd '/demo_ws/install/dual_iiwa_control/lib/dual_iiwa_control/robot_controller --robot_id 1 --gui --ros-args'].
Demo ran successfully.

**Comment by Borailuce99** [comment]
ERROR DOCKER

----- Terminal Output -----
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-05-31-18-21-43-340697-bope-Victus-by-HP-Laptop-16-d0xxx-1
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_controller-1]: process started with pid [70]
[INFO] [1685550103.458877428] [UnityEndpoint]: Starting server on 0.0.0.0:10000
[robot_controller-1] pybullet build time: May 20 2022 19:44:17
[robot_controller-1] Traceback (most recent call last):
[robot_controller-1]   File "/demo_ws/install/dual_iiwa_control/lib/dual_iiwa_control/robot_controller", line 11, in <module>
[robot_controller-1]     load_entry_point('dual-iiwa-control==0.0.0', 'console_scripts', 'robot_controller')()
[robot_controller-1]   File "/demo_ws/install/dual_iiwa_control/lib/python3.8/site-packages/dual_iiwa_control/robot_controller.py", line 691, in main
[robot_controller-1]     controller_node = RobotController(args.robot_id,
[robot_controller-1]   File "/demo_ws/install/dual_iiwa_control/lib/python3.8/site-packages/dual_iiwa_control/robot_controller.py", line 208, in __init__
[robot_controller-1]     self.robot = IiwaSim(robot_model=self.robot_urdf_file,
[robot_controller-1]   File "/demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/iiwa_pb.py", line 214, in __init__
[robot_controller-1]     super().__init__(
[robot_controller-1]   File "/demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/base_robot.py", line 73, in __init__
[robot_controller-1]     self.init_kdl(
[robot_controller-1]   File "/demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/base_robot.py", line 255, in init_kdl
[robot_controller-1]     self.urdf_data = URDF.load(self.robot_file)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 3729, in load
[robot_controller-1]     return URDF._from_xml(node, path)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 3926, in _from_xml
[robot_controller-1]     kwargs = cls._parse(node, path)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 161, in _parse
[robot_controller-1]     kwargs.update(cls._parse_simple_elements(node, path))
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 137, in _parse_simple_elements
[robot_controller-1]     v = [t._from_xml(n, path) for n in vs]
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 137, in <listcomp>
[robot_controller-1]     v = [t._from_xml(n, path) for n in vs]
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 181, in _from_xml
[robot_controller-1]     return cls(**cls._parse(node, path))
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 161, in _parse
[robot_controller-1]     kwargs.update(cls._parse_simple_elements(node, path))
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 137, in _parse_simple_elements
[robot_controller-1]     v = [t._from_xml(n, path) for n in vs]
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 137, in <listcomp>
[robot_controller-1]     v = [t._from_xml(n, path) for n in vs]
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 1146, in _from_xml
[robot_controller-1]     kwargs = cls._parse(node, path)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 161, in _parse
[robot_controller-1]     kwargs.update(cls._parse_simple_elements(node, path))
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 127, in _parse_simple_elements
[robot_controller-1]     v = t._from_xml(v, path)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 181, in _from_xml
[robot_controller-1]     return cls(**cls._parse(node, path))
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 161, in _parse
[robot_controller-1]     kwargs.update(cls._parse_simple_elements(node, path))
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 127, in _parse_simple_elements
[robot_controller-1]     v = t._from_xml(v, path)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/urdf.py", line 581, in _from_xml
[robot_controller-1]     meshes = load_meshes(fn)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/urdfpy/utils.py", line 225, in load_meshes
[robot_controller-1]     meshes = trimesh.load(filename)
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/trimesh/exchange/load.py", line 116, in load
[robot_controller-1]     ) = parse_file_args(file_obj=file_obj,
[robot_controller-1]   File "/usr/local/lib/python3.8/dist-packages/trimesh/exchange/load.py", line 630, in parse_file_args
[robot_controller-1]     raise ValueError('string is not a file: {}'.format(file_obj))
[robot_controller-1] ValueError: string is not a file: /demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/urdf/meshes/iiwa_14/link_0.obj
[robot_controller-1] Exception ignored in: <function IiwaSim.__del__ at 0x7f79c84708b0>
[robot_controller-1] Traceback (most recent call last):
[robot_controller-1]   File "/demo_ws/install/cobot_py/lib/python3.8/site-packages/cobot_py/robots/iiwa_pb.py", line 331, in __del__
[robot_controller-1]     if not self.external_pb:
[robot_controller-1] AttributeError: 'IiwaSim' object has no attribute 'external_pb'
[ERROR] [robot_controller-1]: process has died [pid 70, exit code 1, cmd '/demo_ws/install/dual_iiwa_control/lib/dual_iiwa_control/robot_controller --robot_id 1 --gui --ros-args'].
Demo ran successfully. ✔

**Comment by Borailuce99** [comment]
Ahora el error que aparece al hacer el rebuild con la opción 'c' es:
executor failed running [/bin/bash -c sudo apt-get update -y &&     rosdep install --from-paths src --ignore-src --rosdistro foxy -y -r]: exit code: 1
Error building docker image.
![imagen](https://github.com/ajardon/TFM-BorjaPerez/assets/69549100/53300eb3-c2cb-4dd5-8322-5417d71c2f71)
![imagen](https://github.com/ajardon/TFM-BorjaPerez/assets/69549100/f321f5da-56ad-49d6-ae31-f08fa0d656a6)

**Comment by imontesino** [comment]
Creo que el error es que o has hecho build de nvidia-ros antes o algo similar, he acrualizado la herramienta para que sea mas evidnte el error. haz git pull y pip install y prueba otra vez

**Comment by Borailuce99** [comment]
La opción 4 del roboasset-cli la debería de usar para limpiar los dockers? O al hacer el rebuild con la opción 'y' o 'c' ya se reinstala de 0?

**Comment by Borailuce99** [comment]
Sigue fallando el "labrynth-demo". Los pasos que he seguido son:
- git pull (en la carpeta 'roboasset-ros2-pkgs')
- pip install .
- roboasset-cli
- opción 2 (Build a docker image)
 - opción Nvidia (y)
 - 1 (roboasset_demo)
 - c (rebuild with no cache)
Una vez finalizado todo sin errores
- opción 1 (Run the demos)
 - opción Nvidia (y)
 - opción 1 (Demos with the IIWA robots)
 - `Enter` (tag latest)
 - opción 3 (labrynth-demo)
 - opción 1 (sim_gui_demo)
Se lanza el comando:
-----Command-----
    docker run -it --rm --net=host --volume /dev/shm:/dev/shm --env="DISPLAY" --env "XAUTHORITY=/root/.Xauthority" -v $HOME/.Xauthority:/root/.Xauthority:rw -v  \
/tmp/.X11-unix:/tmp/.X11-unix:rw --runtime=nvidia --gpus all ghcr.io/roboticslab-uc3m/roboasset-demo:latest /bin/bash -c "source /opt/ros/foxy/setup.bash 
 source /demo_ws/install/setup.bash
ros2 run ros_tcp_endpoint default_server_endpoint &
ros2 launch dual_iiwa_control sim_robot_1.launch.py" \
-----------------
Por último se abre por 1s una ventana en negro y se cierra, dando el error:
![imagen](https://github.com/ajardon/TFM-BorjaPerez/assets/69549100/da83e579-c6ac-4983-b58c-01c3d7898f82)

**Comment by ajardon** [comment]
@Borailuce99  ¿Has podido ponerte con esto ? ¿Alguna novedad?
